const APP_STATUS = {
  IDLE: "IDLE",
  READING_FILE: "READING_FILE",
  FILE_ERROR: "FILE_ERROR",
  FILE_READY: "FILE_READY",
  VALIDATING: "VALIDATING",
  VALIDATION_READY: "VALIDATION_READY",
  UPDATING: "UPDATING",
  DONE: "DONE",
};

export default APP_STATUS;
